revise route quota alert types
equinix/equinix-cloudevents pull request #11
Opened 2024-12-10 18:41 UTC by ryli17

## Checklist
- [ ] I have read the [CONTRIBUTING.md](../CONTRIBUTING.md)
- [ ] I certify that my `preview` and `released` lists for Events/Metrics/Alerts are correct
- [ ] I certify that all Events/Metrics/Alerts in `released` are properly tested and ready for production

2025-01-08 00:02 UTC, thogarty requested changes

2025-01-08 00:02 UTC, thogarty commented on jsonschema/equinix/fabric/v1/ChangeEvent.json
> +            "equinix.fabric.connection.bgpipv4_session_status.established",
Lists format have been modified to be list of objects with name and description attributes instead of a list of strings. Please see https://github.com/equinix/equinix-cloudevents/pull/17 as reference.

2025-01-08 00:02 UTC, thogarty commented on jsonschema/equinix/fabric/v1/MetricAlert.json
> +            "equinix.fabric.connection.installed_routes_ipv4.utilization",
Lists format have been modified to be list of objects with name and description attributes instead of a list of strings. Please see https://github.com/equinix/equinix-cloudevents/pull/17 as reference.

2025-01-11 00:07 UTC, ryli17 commented
Included in PR #19

2025-01-11 00:07 UTC, closed without merging