Network Edge Events Published
equinix/equinix-cloudevents pull request #12
Opened 2024-12-14 00:13 UTC by shyamchalla

2024-12-16 21:18 UTC, ryli17 requested changes

2024-12-16 21:18 UTC, ryli17 commented on jsonschema/equinix/network_edge/v1/ChangeEvent.json
> +            "equinix.network_edge.device.reboot.completed";
Please fix the syntax error by removing `;`.

2024-12-17 19:03 UTC, ryli17 approved these changes

2025-01-08 00:02 UTC, thogarty requested changes

2025-01-08 00:02 UTC, thogarty commented on jsonschema/equinix/network_edge/v1/ChangeEvent.json
> +            "equinix.network_edge.device.state.created",
Lists format have been modified to be list of objects with name and description attributes instead of a list of strings. Please see https://github.com/equinix/equinix-cloudevents/pull/17 as reference.

2025-01-08 00:15 UTC, ryli17 commented on jsonschema/equinix/network_edge/v1/ChangeEvent.json
> +            "equinix.network_edge.device.state.created",
Please revise it in ChangeEvent.json.

2025-01-08 00:17 UTC, ryli17 requested changes
Please revise code as Tim mentioned.

2025-01-08 21:33 UTC, ryli17 requested changes

2025-01-08 21:33 UTC, ryli17 commented on DataLoader.json
> +            ],
Please don't change DataLoader.json, catalog.json, and README.md manually. They will be generated automatically. Please make sure the github actions succeeded.l

2025-01-08 21:33 UTC, ryli17 commented on jsonschema/equinix/network_edge/v1/ChangeEvent.json
> +                "description": ""
Please add all descriptions. It can be similar to the corresponding message. The PR #17 has those values empty for placeholder purpose. We are working to add descriptions, as well.

2025-01-09 17:55 UTC, jonawong commented
Hi do we have an ETA on this? We will need to get this out as soon as possible.

2025-01-09 18:14 UTC, closed without merging