CRH Cloud event update
equinix/equinix-cloudevents pull request #14
Opened 2024-12-18 17:11 UTC by timmy-equinix

CRH Observability event schema

2024-12-18 18:05 UTC, ryli17 requested changes
This json is intend to define `data` object in the cloudevent. Thus it is used in `dataschema` in cloudevent. It is not to define the cloudevent metadata. Please refer to other files in fabric domain.

2025-01-08 00:04 UTC, thogarty requested changes

2025-01-08 00:04 UTC, thogarty commented on jsonschema/equinix/resource_manager/v1/ChangeEvent.json
> +        "SpecVersion": {
Definitions aren't properly defined. You're creating many different model types in your definition that should just be properties of a single model definition. See https://github.com/equinix/equinix-cloudevents/blob/0bc5e78e5da9837ae4d51ad29a462de5039c4104/jsonschema/equinix/fabric/v1/ChangeEvent.json#L10 for reference.

2025-01-08 00:05 UTC, thogarty requested changes

2025-01-08 00:05 UTC, thogarty commented on jsonschema/equinix/resource_manager/v1/ChangeEvent.json
> -    },
Leave these definitions at the end of the file, and all must be included. Remove the attribute from the beginning of the file on line https://github.com/equinix/equinix-cloudevents/pull/14/files#diff-b53020bebf4fb260b25992533608a4bab6f840f83b568f62804d114cdb147f72R7-R8

2025-01-13 03:04 UTC, timmy-equinix commented on jsonschema/equinix/resource_manager/v1/ChangeEvent.json
> +        "SpecVersion": {
Thank you @thogarty , updated with correct version.

2025-01-13 03:05 UTC, timmy-equinix commented on jsonschema/equinix/resource_manager/v1/ChangeEvent.json
> -    },
Added released tags

2025-01-15 02:18 UTC, timmy-equinix commented on jsonschema/equinix/resource_manager/v1/ChangeEvent.json
> +                "description": "Org / Project deleted event."
Thanks ryan, updated accordingly.

2025-01-15 02:20 UTC, timmy-equinix commented on jsonschema/equinix/resource_manager/v1/ChangeEvent.json
> -            "additionalProperties": true,
added as required, thanks

2025-01-15 02:20 UTC, timmy-equinix commented on jsonschema/equinix/resource_manager/v1/ChangeEvent.json
> -                    "additionalProperties": true,
added as required, thanks

2025-01-15 18:00 UTC, ryli17 commented
1) Please rebase to main brunch
2) Please don't change catalog.json, DataLoader.json, and README.md. They will be generated automatically.
2) Please make sure github actions pass validation.

2025-02-03 20:51 UTC, ryli17 approved these changes

2025-02-10 20:58 UTC, thogarty approved these changes

2025-02-13 07:14 UTC, mvaiyali approved these changes

2025-02-13 07:15 UTC, merged