PAM-7782:publish AM audit event schema to equinix-cloudevents repository
equinix/equinix-cloudevents pull request #15
Opened 2024-12-18 20:19 UTC by hawang0456

2025-01-08 00:00 UTC, thogarty requested changes

2025-01-08 00:00 UTC, thogarty commented on DataLoader.json
> +                "equinix.access_manager.user.role.added",
Lists format have been modified to be list of objects with `name` and `description` attributes instead of a list of strings. Please see https://github.com/equinix/equinix-cloudevents/pull/17 as reference.

2025-01-08 00:04 UTC, ryli17 requested changes

2025-01-08 00:04 UTC, ryli17 commented on jsonschema/equinix/access_manager/v1/RoleAssignmentEvent.json
> +     ]
Please rebase new changes from main and then add description to each type:
```
"preview": [
                {"name":"equinix.access_manager.user.role.added",
                  "description": "<please add description similar to message>"
               },
              {"name": "equinix.access_manager.user.role.removed",
                "description": "<description similar to message>"
             }
     ]
```

2025-01-08 00:04 UTC, ryli17 commented on jsonschema/equinix/access_manager/v1/RoleAssignmentEvent.json
> +       },
Is the `resource` a list?

2025-01-08 02:24 UTC, hawang0456 commented on DataLoader.json
> +                "equinix.access_manager.user.role.added",
Looked like the change for DataLoader.json was automatically overwrite by:   
https://github.com/equinix/equinix-cloudevents/pull/15/commits/12e8c2375e576dfc79aecca4f2ead3e7c0656dcf

2025-01-08 21:21 UTC, ryli17 approved these changes
looks good to me.

2025-01-10 22:38 UTC, satyav-equinix commented on jsonschema/equinix/access_manager/v1/RoleAssignmentEvent.json
> +   "resource": {
Hi @thogarty  @ryli17 , resource inside payload is resource scope of roleAssignment. Can we leave it  as is?

2025-01-14 00:59 UTC, hawang0456 commented on jsonschema/equinix/access_manager/v1/RoleAssignmentEvent.json
> +   "resource": {
Updated.

2025-01-14 01:10 UTC, ryli17 approved these changes
lgtm

2025-01-14 06:02 UTC, thogarty approved these changes
LGTM. Thanks @hawang0456 !

2025-01-15 02:22 UTC, timmy-equinix approved these changes

2025-01-15 02:48 UTC, merged